#!/bin/bash
CC="gcc"

if [ "$1" == "++" ]; then
    CC="g++";
    echo $1
fi

CFLAGS="-lSDL2 -lGLEW -lGL -lGLU -lm -lpthread -lX11"
COPT="-O2 -march=native -mtune=native"

SOURCE="*.c"
OUTPUT="meshviewer"

$CC $COPT $CFLAGS $SOURCE -o $OUTPUT
